CREATE TABLE [dbo].[UserSessionArchive]
(
	[Id] BIGINT NOT NULL PRIMARY KEY NONCLUSTERED,
	UserId BIGINT NULL,
	SessionKey UNIQUEIDENTIFIER NOT NULL,
	UserAgent NVARCHAR(500) NULL,
	UserIp NVARCHAR(255) NULL,
	DateCreated DATETIME DEFAULT(GETUTCDATE()) NOT NULL,
    [DateLastUpdated] DATETIME NOT NULL DEFAULT (GETUTCDATE()),
    [DateToExpire] DATETIME NOT NULL DEFAULT (DATEADD(minute, 15, GETUTCDATE())),
    [SessionData] VARBINARY(MAX) NULL,
	CONSTRAINT FK_UserSessionArchive_User FOREIGN KEY (UserId) REFERENCES [dbo].[User] (Id)
)
